server:
  port: 8080
logging:
  file:
    path: /var/log
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:info}
      jooq: info
spring:
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:project}?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
      schema-locations: classpath:db/schema.sql
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
management:
  metrics:
    binders:
      processor:
        enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
jwt:
  secret: ${JWT_SECRET}
  expiration-min: ${JWT_EXPIRATION_MIN:100}
  cookie-name: ${JWT_COOKIE_NAME:jwt}
