server:
  port: 8080
logging:
  file:
    path: /var/log
  level:
    org:
      springframework:
        security: debug
      jooq: info
spring:
  main:
    web-application-type: servlet
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:project}?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
management:
  metrics:
    binders:
      processor:
        enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
jwt:
  secret: "secret"
  expiration-min: 100
  cookie-name: "jwt"
